name: Black Formatter

on:
  pull_request:
  workflow_dispatch:

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f setup/github-actions.txt ]; then 
            pip install -r setup/github-actions.txt; fi
      - name: Run formatter
        run: |
          black . --check --diff --color

          result=$?

          if [ $result -ne 0 ]; then
              echo "Formatter Failed"
              exit $result
          fi
          echo "Formatter Passed"
          exit $result
