name: Docs

on:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f setup/github-actions.txt ]; 
          then pip install -r setup/github-actions.txt; fi
      - name: Generate docs
        run: |
          python -m pdoc --html -o docs onepassword -f
          mv docs/onepassword/* docs/
          rm -rf docs/onepassword

          if [ -f onepassword.html ]; then
            exit 0
          fi

          exit 1

